#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = new \Symfony\Component\Console\Application("Welcome from console", "v1.0.0");
$app->add(new \GlebecV\SumCommand());
$app->run();
