#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use GlebecV\SumCommand;

$app = new Application("Welcome from console", "v1.0.0");
$app->run();

//echo 'Hi'.PHP_EOL;
